### ISSUE TITLE
Class 'Inspheric\Fields\IndicatorFieldServiceProvider' not found

### ISSUE THREAD

**Issue by ekandreas** [inspheric/nova-indicator-field#11]
When running composer require, error message appears:
Class 'Inspheric\Fields\IndicatorFieldServiceProvider' not found

**Comment by ekandreas** [comment]
Latest version.

Solve it via composer.json update:
```
    "extra": {
        "laravel": {
            "dont-discover": [
                "laravel/dusk",
                "inspheric/nova-indicator-field"
            ]
        }
    },
```

**Comment by kitbs** [comment]
Thanks. This was due to the incorrect filename. I have released a new version which should solve this without need for your Don't Discover workaround.
