### ISSUE TITLE
Works with INT field values?

### ISSUE THREAD

**Issue by msassa** [inspheric/nova-indicator-field#12]
I have a integer field in the database that indicate the status, and only see a blank field in the nova resource.

I used as:
```
Indicator::make('status')
                ->labels(
                    [
                        '0'   => 'Pendiente',
                        '1'   => 'En proceso',
                        '2'   => 'Completa',
                        '3'   => 'Cerrada',
                        '4'   => 'Vencida',
                        '100' => 'Eliminada',
                        '101' => 'Sin Proveedores',
                    ]
                ),
```

Also I try:
```
Indicator::make('status')
                ->labels(
                    [
                        0   => 'Pendiente',
                        1   => 'En proceso',
                        2   => 'Completa',
                        3   => 'Cerrada',
                        4   => 'Vencida',
                        100 => 'Eliminada',
                        101 => 'Sin Proveedores',
                    ]
                ),
```

and only get this:
![image](https://user-images.githubusercontent.com/570080/73068140-38a4fd80-3e89-11ea-8e99-57c4e29bdda0.png)

**Comment by kitbs** [comment]
Hi @msassa 

I have set up the same field definition as you and the field is displayed with no problems:

![image](https://user-images.githubusercontent.com/4569320/73068941-60ee2580-3ea4-11ea-8694-230e2a30c7a6.png)
![image](https://user-images.githubusercontent.com/4569320/73068960-719e9b80-3ea4-11ea-9ca2-d527185cc77a.png)

Have you made sure to run `php artisan nova:publish`?

**Comment by msassa** [comment]
Yes, I have publish the nova assets.
Now is working! I think my mistake was I wasn't full reload the page.
Sorry!
