### ISSUE TITLE
Breaks style

### ISSUE THREAD

**Issue by mingyoung** [inspheric/nova-indicator-field#2]
![image](https://user-images.githubusercontent.com/6228858/46252396-bece5100-c49a-11e8-9df2-00a55a0cf6c9.png)

**Comment by kitbs** [comment]
哼，很奇怪！

The HTML and style for this field is the same as Nova's own `Boolean` field. Can you test whether using a Boolean field with Chinese labels displays in the same way?

If the Boolean field is also broken, you should raise an issue at [laravel/nova-issues](https://github.com/laravel/nova-issues/issues) and link it back here. If not, let me know and I'll look into why it displays like this.

谢谢

**Comment by kitbs** [comment]
I cannot replicate this.

**Comment by mingyoung** [comment]
Oh, forget about it. Never mind, just forget it :)
