### ISSUE TITLE
Add custom colors

### ISSUE THREAD

**Issue by bigperson** [inspheric/nova-indicator-field#3]
How to i can add custom colors?
```php
Indicator::make('Status')
    ->colors([
        'banned' => '#a466bd',
        'active' => '#a2c617',
        'invited' => '#e92919',
        'inactive' => '#000000',
    ])
```

**Comment by kitbs** [comment]
You aren't able to do this in the way you have described yet, but I might look at it if I get time. I'd be happy to review a pull request too.

What you could do for now is serve your own CSS file (using Nova's Asset functionality) and add your own classes with the background colours defined.

The classes must be named e.g. `indicator-*yourcolourname*` so your CSS would be:

```css
.indicator-yourcolourname {
    background: #000000;
}
```
and your Field definition would be:
```php
Indicator::make('Status')
    ->colors([
        'yourstatus' => 'yourcolourname',
    ])
```

**Comment by ppisecky** [comment]
Wouldn't this be pretty easy to implement just by using a regex to check for `#` followed by 3 or 6 alphanumerical characters?

This would make this package synergize very nicely with https://novapackages.com/packages/timothyasp/nova-color-field

**Comment by kitbs** [comment]
I am implementing this now. If the colour string starts with # it will be interpreted as a background-color, otherwise as a class.
