### ISSUE TITLE
Doesn’t work with model accessors

### ISSUE THREAD

**Issue by RicLeP** [inspheric/nova-indicator-field#4]
I’ve a table with a renewal date field (timestamp) and what to show a status. If the renewal date field has expired then I want to display fact. Here’s my code - but it just shows a dash and no label on the index view.

// Model

	public function membershipStatusAttribute() {
		if ($this->renewal_date < now()) {
			return 'expired';
		} else {
			return 'valid';
		}
	}

// Nova resource

	Indicator::make('membership_status')
		->labels([
			'expired' => 'Expired',
			'valid' => 'Valid',
		])->colors([
			'expired' => 'red',
			'valid' => 'green',
		]),

**Comment by kitbs** [comment]
The syntax for Eloquent model accessors is "get...Attribute", so your first example needs to be getMembershipStatusAttribute, not membershipStatusAttribute. The resource syntax is correct.
